path: /home/shin/Desktop/cordinate_ws/src/cordinate/map/wide_factory.csv
map_yaml: /home/shin/Desktop/cordinate_ws/src/cordinate/map/wide_factory.yaml
map_pgm: /home/shin/Desktop/cordinate_ws/src/cordinate/map/wide_factory.pgm