path: /home/shin/Desktop/cordinate_ws/src/cordinate/map/new_factory4.5.csv
map_yaml: /home/shin/Desktop/cordinate_ws/src/cordinate/map/new_factory.yaml
map_pgm: /home/shin/Desktop/cordinate_ws/src/cordinate/map/new_factory.pgm